seattleflu/switchboard

bin/export-record-barcodes, datasette.yaml, templates/pages/dial.html
When a barcode is dialed matching multiple records, redirect users to the canned `lookup-barcode` query. 
Add back end scan date to the exported data from REDCap, a field the lab requested that will be helpful for them in record disambiguation.
=> Duplicate barcodes

templates/index.html, templates/pages/dial.html
Provides a way to and from the dialer other than modifying the URL
directly.
Overrides the default Datasette home page to provide a short menu of
destinations.  Adds the Datasette nav bar styles to the dialer for
getting back to the home page.
=> Navigation to and from the dialer (/dial)

Makefile
Otherwise Datasette hits transient errors because either the file doesn't exist (after the initial rm) or one of the tables doesn't yet exist.
=> Update SQLite database atomically

Makefile, Pipfile, Pipfile.lock
This moves the update from the filesystem layer into the SQL layer, thus
allowing multiple processes to coordinate.  Datasette holds open SQLite
connections and was keeping references to the deleted files.
The new --truncate option to `sqlite-utils insert` is added in a PR I
submitted <https://github.com/simonw/sqlite-utils/pull/118>.  For now,
sqlite-utils is installed from our fork.  When/if --truncate is released
officially, we can switch back to installing from PyPI.
Resolves #10.
--- 
Alternate to #11.
=> Update records in SQLite via SQL instead of re-creating the database/file

bin/export-record-barcodes
We started seeing consistent TimeoutErrors thrown in production.  This
happened after a major REDCap upgrade, but it's not clear if it's
related on not.
The timeouts appear to be arising from the OS-level networking stack
since we don't set an explicit timeout for the "requests" library and
the exception isn't the Python-level socket library timeout class
socket.timeout.
On a hunch that REDCap can no longer service as many connections
simultaneously, reduce from 15 → 8.  Since we currently have 16
projects, each thread will take 2 projects.
=> Reduce number of simultaneous connections to REDCap

bin/export-record-barcodes
We're still getting HTTP connect timeouts after we switched from 15 to 8 threads. This change sets the max threads to 1. A backoffice change will decrease the frequency with which this make gets invoked.
=> Set ThreadPoolExector max threads to 1

README.md, bin/export-record-barcodes, datasette.yaml, derived-tables.sql
This PR incorporates the UW Reopening REDCap project (Husky Coronavirus Testing) into the SCAN Switchboard. 
This is the first step in pulling HCT records -- we are not yet deep linking to particular repeat instances or dropping users into the PCDEQC form yet.
Tom suggested that we get this step out the door first, and both I and the lab agreed that this was a good idea.
=> Husky testing first pass

Makefile
Switchboard users are complaining that sometimes when they search
for a valid barcode they get no results and then later they do. Looking
at how sqlite-utils populates the table, we see the potential for this
happening: the delete and the insert are not in the same transaction,
and with a growing number of records to insert, inserting all records is
taking longer. This means that there is a moment when the table is empty
and many moments before all the records are inserted into the table.
This commit causes sqlite-utils to insert the records into a temporary
table (not a temp table in the DB sense, but a table with 'new' appended
to its name). A sqlite3 command drops the existing table and renames
the new table to the real table name in a transaction.
=> Insert records into 'new' table then rename tables

derived-tables.sql
I'm sending this out as a PR so that you can see the change and how I reproduced the situation. I'm going to go ahead and merge and deploy it to see if this makes the error go away.
We are seeing instances where datasette is locking the sqlite database
and causing the `derived-tables.sql` task to fail with the error
`database is locked`.
This commit adds a 10 second timeout to the top of the SQL file.
This will let the command wait up to 10 seconds for the lock to
get removed so that it can run.
To reproduce the error run this batch:
for i in {1..100}
do
sqlite3 data/sfs-redcap.sqlite < derived-tables.sql
done
And while that's running use datasette to access a barcode like:
http://127.0.0.1:3002/sfs-redcap/lookup-barcode?barcode=aaaaaaaa
Run that query a few times in a row and without the …
=> Add timeout to SQL command

README.md, bin/serve, templates/pages/dial.html
Switchboard users have reported getting a
`TypeError: Cannot read property 'length' of undefined`
error when trying to look up a barcode. This is an intermittent
error, and we tracked this back to to the sqlite database being
locked while records are loading.
This commit adds a timeout to datasette config to let a query
try for 10 seconds (instead of the default of 1 second). This should
accommodate periods when the query needs to wait for the database
to be available.
In here we also look for the specific error situation and show a
clearer exception message.
=> Add datasette timeout

bin/export-record-barcodes, datasette.yaml
Originally, 15 threads were used to pull records from REDCap
simulatenously. That proved too much, and we started seeing TimeOut
errors. We then tried 8 threads. That worked for a while, but we started
getting timeouts again, so we went all the way down to 1 thread. I just
ran many times locally with 5 threads and never got an error. This cuts
the REDCap record gathering time from 110 seconds (1 thread) to half,
55 seconds (5 threads). I went crazy and tried 25 threads. The gathering
took 46 seconds. Keeping the thread count low so that we don't hit
timeouts seems worth an extra 10 seconds.
=> Use 5 threads for pulling REDCap records

bin/export-record-barcodes
The SCAN: IRB - Urdu project has been deleted from REDCap. Remove it
from our barcodes export script so that we don't encounter 400 errors
from REDCap when retrieving data from a non-existent project.
=> Drop the SCAN IRB Urdu project

templates/pages/dial.html
Barcodes still should only be 8 characters made up of only 0–9 and A–F.
However, we fairly frequently get mistyped barcodes in REDCap due to
user error. We want to be able to use the Switchboard to quickly look
up incorrectly entered barcodes to pin them down in REDCap. Therefore,
loosen the input field restrictions in the Switchboard app so we can
look up "bad" barcodes, too.
Relax the restriction for number of characters from 8 to 6+ as
sometimes we receive truncated barcodes. Don't bother looking up
barcodes of 5 characters or fewer for now, because I assume the user
hasn't finished typing. (We can relax the number of characters
restriction again if we start receiving barcodes truncated to less than
6 characters in REDCap).
Also drop the restriction on the range of acceptable alphabet …
=> Modify input barcode field restrictions

README.md, bin/export-record-barcodes
Makes for easier, unified handling across our codebases and so many
REDCap projects.
=> Switch to new-style env vars for REDCap API credentials

README.md, bin/export-record-barcodes, datasette.yaml, derived-tables.sql
Include barcodes from Adult Family Homes and Workplace Outbreaks on the
switchboard. This project is a "classic" RedCAP project, such that it is not
longitudinal and does not have events or arms. The RedCAP API call to fetch
events will fail for classic projects, and we don't actually need to provide
and arm or event to construct the deep link URL into the PCDEQC instrument for
records in this classic project. Include barcode variables
(core_collection_barcode and return_collection_barcode) from the new project.
Constructed the RedCAP project using the new style, without explicitly passing
the token. This required updating the ID3C library, and I refreshed the
versions of other dependencies along with it.
=> Include barcodes from AFH and Workplace Outbreaks

README.md, bin/export-record-barcodes, datasette.yaml, derived-tables.sql
1. Add the Apple Respiratory Study to Switchboard.
2. Add missing projects to the README.
NOTE: Because this PR adds columns to the record_barcodes table in Sqlite, when this is deployed we will need to delete the database files and let the MAKE recreate them. Do this before or after work hours as not to affect users.
=> Add Apple Respiratory Study

bin/export-record-barcodes
REDCap Project.records now supports a page_size so that all the
project's records don't have to be pulled from REDCap at once.
Configure this for the HCT project so that the call to REDCap doesn't
error out.
=> Add fetch_page_size property to Project for chunking

Makefile
Explicitly set the SQLite database to the WAL mode. This handles
the scenario when we delete the database files and let the code create
new ones after we modify the columns in the underlying tables. Without
explicitly setting WAL mode, the database would stay in the 'delete'
(the default) mode.
Setting WAL mode when the database is already in WAL mode in a no-op.
=> Enable SQLite WAL mode in the Makefile

Makefile, README.md, bin/export-record-barcodes, constraints.txt, import.sql, requirements.in, requirements.txt
Reduces import time from ~10 min to ~1 min.
Requires switching from NDJSON to CSV, but we now no longer need the
sqlite-utils program and can embed the .import command within a
transaction ourselves instead of importing into a second table and
renaming.
=> Import records via SQLite's builtin .import command

bin/export-record-barcodes, datasette.yaml, derived-tables.sql
The CSV DictWriter was writing the JSON for the `record_link` column
using a single quote instead of a double quote around the JSON key names
and values. This was causing a `json.loads` error in html_links.py.
With this change, we don't store the JSON in the table. Instead,
at query time, the SQL concatenates to build the JSON. The two components
that go into the JSON are `record_url` which was already a column
and a new column named `record_link_label`.
=> Generate record link JSON at query time

bin/export-record-barcodes
Do not deploy this change until the 2 REDCap projects have been put into production mode. They were copied with real records from the English project.
=> Add Snohomish Schools Russian and Spanish projects

README.md, bin/export-record-barcodes
Include the Yakima Radxup study English and Spanish projects in switchboard data.
There were no new fields to add, because this is based on the snohomish project.
This just adds the event id mapping for the new redcap projects.
Before deploy:
=> Include Yakima Radxup projects

bin/export-record-barcodes
Looking up REDCap records by CLIA barcode is useful when the collection
barcode is missing or wrong.
I created this list of fields by programmatically querying the fields of
all projects we interact with, grepping for any that mention CLIA, and
then manually reviewing/curating from there.
=> Include CLIA barcodes in dataset

requirements.in, requirements.txt
We see sporadic errors from REDCap related to bad JSON responses, and
it'll be nice to have more detailed logging of what was returned.
=> Upgrade pinned ID3C version for better JSON response logging

README.md, bin/export-record-barcodes
HCT 2021-2022 project is running on a new dedicated HCT REDCap
instance. Adding required URL and project information to export
data from ITHS and HCT REDCap servers. This requires a new environment
variable for `REDCAP_API_TOKEN_hct.redcap.rit.uw.edu_45` which will
need to be added to production server on deployment.
=> Add new REDCap instance URL and HCT project

README.md, bin/export-record-barcodes
Adding the SCAN: Tiny Swabs project to switchboard. This project design
includes two new field names that are being used to store barcodes.
Those are added to the list of barcode fields to be included during export.
=> Add scan tiny swab project

bin/export-record-barcodes
Overnight, the API token being used for this project on the backoffice server became invalid and is affecting the Switchboard refresh job. A majority of the team have lost access to the project. As a temporary fix, the project is commented out of the Switchboard pipeline. This project does not receive any new samples and is currently on cleanup/analysis on REDCap.
=> Disable REDCap Project 34101 from Switchboard

bin/export-record-barcodes
Correction to last deployment: Project of interest is commented out with # at the beginning of each line instead of multiline comment syntax.
Testing: Was not able to test locally b/c I do not have API export privileges for many old pre-IRB REDCap projects, thus could not run `make`.
Context: Overnight, the API token being used for this project on the backoffice server became invalid and is affecting the Switchboard refresh job. A majority of the team have lost access to the project. As a temporary fix, the project is commented out of the Switchboard pipeline. This project does not receive any new samples and is currently on cleanup/analysis on REDCap.
=> Disable REDCap Project 34101 from Switchboard - Correction

requirements.in, requirements.txt
Looks like the version of id3c specified is forcing us to downgrade some of its deps. These version specifications are hardcoded here: https://github.com/seattleflu/id3c/blob/master/setup.py
We may need to remove some of them, especially for Python 3.9, but I haven't seen anything break yet. Just something to keep in mind.
=> Update id3c to latest master

README.md, bin/export-record-barcodes
We recently lost access to the Yakima study (REDCap PID 34101) and will not be getting our access back, so are removing it from the project list. Also included this change is the removal of the Spanish Pilot version of this study (PID 34701) which we still have access to but will likely lose in the future. This change will preempt those run failures for the Spanish project.
=> Remove Yakima Studies from Project List

README.md, bin/export-record-barcodes
- Remove ended studies from the switchboard.
As those studies are not collecting new data,
it is no longer necessary for them to be included.
Removing them will reduce unnecessary processing for us
and for REDCap, and keeps our code base tidy.
- Fix broken link in README
=> Clean up ended studies from switchboard

bin/export-record-barcodes
The switchboard job has been timing out more recently. This change batches
data export requests to the SCAN English project to hopefully reduce the
load on the REDCap API during the switchboard refresh job to prevent timeouts
when exporting data.
=> Batch Data Export Requests for SCAN English

bin/export-record-barcodes
Using lots of API calls for updating the switchboard with SCAN records,
so commenting them out for now to try and alleviate some of the strain.
=> Remove SCAN Updating from Switchboard

README.md, bin/export-record-barcodes, requirements.in, requirements.txt
Now that SCAN study has ended sample collection, we can
remove the associated REDCap projects from this app.
=> Remove SCAN and old HCT projects

bin/export-record-barcodes
An upgrade to REDCap starting causing API requests to fail if they contained invalid field names. Dropping fields that are no longer part of the codebook and internal REDCap fields that do not need to be specified in the request.
=> Remove invalid REDCap fields
